export type EmojiEntry = {
  char: string;
  shortcode: string;
  name: string;
  group: string;
  keywords: readonly string[];
};

type EmojiRow = readonly [char: string, shortcode: string, group: string, keywords: string];

/**
 * A curated table rather than a full Unicode data set: the desktop bundle stays
 * dependency-free and small, at the cost of the long tail of rare emoji. Rows
 * are `[character, shortcode, group, space separated keywords]`.
 */
const EMOJI_TABLE: readonly EmojiRow[] = [
  ["😀", "grinning", "Smileys", "happy smile grin face joy"],
  ["😃", "smiley", "Smileys", "happy smile open mouth"],
  ["😄", "smile", "Smileys", "happy laugh eyes"],
  ["😁", "grin", "Smileys", "happy beaming"],
  ["😆", "laughing", "Smileys", "haha satisfied lol"],
  ["😅", "sweat_smile", "Smileys", "relief nervous phew"],
  ["🤣", "rofl", "Smileys", "rolling floor laughing lmao"],
  ["😂", "joy", "Smileys", "tears laughing cry lol"],
  ["🙂", "slightly_smiling_face", "Smileys", "smile polite"],
  ["🙃", "upside_down_face", "Smileys", "sarcasm irony silly"],
  ["😉", "wink", "Smileys", "flirt joke"],
  ["😊", "blush", "Smileys", "smile shy happy"],
  ["😇", "innocent", "Smileys", "angel halo"],
  ["🥰", "smiling_face_with_hearts", "Smileys", "love adore crush"],
  ["😍", "heart_eyes", "Smileys", "love crush adore"],
  ["🤩", "star_struck", "Smileys", "excited amazed wow"],
  ["😘", "kissing_heart", "Smileys", "kiss love"],
  ["😗", "kissing", "Smileys", "kiss"],
  ["😋", "yum", "Smileys", "tasty delicious tongue"],
  ["😛", "stuck_out_tongue", "Smileys", "playful tongue"],
  ["😜", "stuck_out_tongue_winking_eye", "Smileys", "playful joke tongue"],
  ["🤪", "zany_face", "Smileys", "goofy wild crazy"],
  ["🤨", "raised_eyebrow", "Smileys", "skeptical suspicious doubt"],
  ["🧐", "monocle", "Smileys", "inspect examine curious"],
  ["🤓", "nerd", "Smileys", "geek glasses smart"],
  ["😎", "sunglasses", "Smileys", "cool shades"],
  ["🥳", "partying_face", "Smileys", "celebrate party horn"],
  ["😏", "smirk", "Smileys", "smug sly"],
  ["😒", "unamused", "Smileys", "meh bored annoyed"],
  ["😞", "disappointed", "Smileys", "sad down"],
  ["😔", "pensive", "Smileys", "sad thoughtful"],
  ["😟", "worried", "Smileys", "concerned anxious"],
  ["🙁", "slightly_frowning_face", "Smileys", "sad frown"],
  ["😣", "persevere", "Smileys", "struggle strain"],
  ["😖", "confounded", "Smileys", "frustrated"],
  ["😫", "tired_face", "Smileys", "exhausted fed up"],
  ["😩", "weary", "Smileys", "tired drained"],
  ["🥺", "pleading_face", "Smileys", "puppy eyes beg"],
  ["😢", "cry", "Smileys", "sad tear"],
  ["😭", "sob", "Smileys", "cry bawling tears"],
  ["😤", "triumph", "Smileys", "steam determined huff"],
  ["😠", "angry", "Smileys", "mad annoyed"],
  ["😡", "rage", "Smileys", "furious mad red"],
  ["🤬", "cursing_face", "Smileys", "swearing symbols angry"],
  ["🤯", "exploding_head", "Smileys", "mind blown shocked"],
  ["😳", "flushed", "Smileys", "embarrassed surprised blush"],
  ["🥵", "hot_face", "Smileys", "heat sweating overheated"],
  ["🥶", "cold_face", "Smileys", "freezing frozen"],
  ["😱", "scream", "Smileys", "fear shock horror"],
  ["😨", "fearful", "Smileys", "scared afraid"],
  ["😰", "cold_sweat", "Smileys", "anxious nervous"],
  ["😥", "disappointed_relieved", "Smileys", "phew sad relief"],
  ["😓", "sweat", "Smileys", "hard work nervous"],
  ["🤗", "hugs", "Smileys", "hug embrace warm"],
  ["🤔", "thinking", "Smileys", "hmm consider ponder"],
  ["🤭", "hand_over_mouth", "Smileys", "oops giggle whoops"],
  ["🤫", "shushing_face", "Smileys", "quiet silence secret"],
  ["🤥", "lying_face", "Smileys", "pinocchio liar"],
  ["😶", "no_mouth", "Smileys", "silent speechless blank"],
  ["😐", "neutral_face", "Smileys", "meh blank deadpan"],
  ["😑", "expressionless", "Smileys", "blank unimpressed"],
  ["😬", "grimacing", "Smileys", "awkward yikes cringe"],
  ["🙄", "roll_eyes", "Smileys", "annoyed whatever"],
  ["😯", "hushed", "Smileys", "surprised stunned"],
  ["😮", "open_mouth", "Smileys", "surprised wow"],
  ["😲", "astonished", "Smileys", "shocked amazed"],
  ["😴", "sleeping", "Smileys", "zzz tired sleep"],
  ["🤤", "drooling_face", "Smileys", "hungry want"],
  ["😪", "sleepy", "Smileys", "tired drowsy"],
  ["😵", "dizzy_face", "Smileys", "knocked out woozy"],
  ["🤐", "zipper_mouth", "Smileys", "silence secret quiet"],
  ["🥴", "woozy_face", "Smileys", "drunk tipsy dazed"],
  ["🤢", "nauseated_face", "Smileys", "sick gross"],
  ["🤮", "vomiting_face", "Smileys", "sick throw up"],
  ["🤧", "sneezing_face", "Smileys", "sick cold tissue"],
  ["😷", "mask", "Smileys", "sick ill medical"],
  ["🤒", "face_with_thermometer", "Smileys", "sick fever ill"],
  ["🤕", "face_with_head_bandage", "Smileys", "hurt injured"],
  ["🤑", "money_mouth_face", "Smileys", "rich dollars profit"],
  ["🤠", "cowboy_hat_face", "Smileys", "yeehaw western"],
  ["😈", "smiling_imp", "Smileys", "devil mischief evil"],
  ["👿", "imp", "Smileys", "devil angry evil"],
  ["💀", "skull", "Smileys", "dead death dying"],
  ["👻", "ghost", "Smileys", "boo halloween spooky"],
  ["👽", "alien", "Smileys", "ufo extraterrestrial"],
  ["🤖", "robot", "Smileys", "bot ai machine"],
  ["💩", "poop", "Smileys", "pile crap bad"],
  ["🎃", "jack_o_lantern", "Smileys", "halloween pumpkin"],
  ["😺", "smiley_cat", "Smileys", "cat happy"],
  ["😻", "heart_eyes_cat", "Smileys", "cat love"],
  ["🙈", "see_no_evil", "Smileys", "monkey hide oops"],
  ["🙉", "hear_no_evil", "Smileys", "monkey deaf"],
  ["🙊", "speak_no_evil", "Smileys", "monkey quiet"],
  ["👍", "thumbsup", "Gestures", "yes approve like +1 ok"],
  ["👎", "thumbsdown", "Gestures", "no disapprove dislike -1"],
  ["👌", "ok_hand", "Gestures", "perfect fine agree"],
  ["🤌", "pinched_fingers", "Gestures", "italian gesture"],
  ["✌️", "v", "Gestures", "peace victory two"],
  ["🤞", "crossed_fingers", "Gestures", "luck hopeful"],
  ["🤟", "love_you_gesture", "Gestures", "ily hand"],
  ["🤘", "metal", "Gestures", "rock horns"],
  ["🤙", "call_me_hand", "Gestures", "shaka hang loose"],
  ["👈", "point_left", "Gestures", "direction left"],
  ["👉", "point_right", "Gestures", "direction right"],
  ["👆", "point_up_2", "Gestures", "direction up this"],
  ["👇", "point_down", "Gestures", "direction down below"],
  ["☝️", "point_up", "Gestures", "one index this"],
  ["✋", "raised_hand", "Gestures", "stop high five halt"],
  ["🤚", "raised_back_of_hand", "Gestures", "stop"],
  ["🖐️", "hand_splayed", "Gestures", "five stop"],
  ["🖖", "vulcan_salute", "Gestures", "spock star trek"],
  ["👋", "wave", "Gestures", "hello goodbye hi"],
  ["🤝", "handshake", "Gestures", "deal agreement partner"],
  ["🙏", "pray", "Gestures", "thanks please namaste hope"],
  ["✍️", "writing_hand", "Gestures", "write note sign"],
  ["💪", "muscle", "Gestures", "strong flex biceps"],
  ["🦾", "mechanical_arm", "Gestures", "prosthetic strong"],
  ["👏", "clap", "Gestures", "applause bravo praise"],
  ["🙌", "raised_hands", "Gestures", "celebrate hooray praise"],
  ["👐", "open_hands", "Gestures", "hug welcome"],
  ["🤲", "palms_up_together", "Gestures", "pray offer"],
  ["🤜", "right_facing_fist", "Gestures", "bump punch"],
  ["🤛", "left_facing_fist", "Gestures", "bump punch"],
  ["✊", "fist", "Gestures", "power solidarity"],
  ["👊", "punch", "Gestures", "fist bump"],
  ["🫡", "saluting_face", "Gestures", "salute respect yes sir"],
  ["🫶", "heart_hands", "Gestures", "love care"],
  ["🧠", "brain", "People", "smart think mind"],
  ["👀", "eyes", "People", "look watch see review"],
  ["👁️", "eye", "People", "look see"],
  ["👶", "baby", "People", "infant child new"],
  ["🧑", "person", "People", "adult human"],
  ["👩", "woman", "People", "female adult"],
  ["👨", "man", "People", "male adult"],
  ["🧓", "older_adult", "People", "senior elder"],
  ["👮", "police_officer", "People", "cop law"],
  ["🕵️", "detective", "People", "spy investigate search"],
  ["👷", "construction_worker", "People", "build helmet work"],
  ["🧑‍💻", "technologist", "People", "developer programmer coder engineer"],
  ["🧑‍🔬", "scientist", "People", "research lab"],
  ["🧑‍🍳", "cook", "People", "chef kitchen"],
  ["🧑‍🚀", "astronaut", "People", "space nasa"],
  ["🦸", "superhero", "People", "hero power"],
  ["🧙", "mage", "People", "wizard magic"],
  ["🧑‍🎓", "student", "People", "graduate school learn"],
  ["🧑‍🏫", "teacher", "People", "school professor"],
  ["🐶", "dog", "Animals", "puppy pet"],
  ["🐱", "cat", "Animals", "kitten pet"],
  ["🐭", "mouse", "Animals", "rodent"],
  ["🐹", "hamster", "Animals", "pet rodent"],
  ["🐰", "rabbit", "Animals", "bunny"],
  ["🦊", "fox", "Animals", "clever"],
  ["🐻", "bear", "Animals", "grizzly"],
  ["🐼", "panda", "Animals", "bear china"],
  ["🐨", "koala", "Animals", "australia"],
  ["🐯", "tiger", "Animals", "cat stripes"],
  ["🦁", "lion", "Animals", "king cat"],
  ["🐮", "cow", "Animals", "moo cattle"],
  ["🐷", "pig", "Animals", "oink"],
  ["🐸", "frog", "Animals", "toad"],
  ["🐵", "monkey_face", "Animals", "ape"],
  ["🐔", "chicken", "Animals", "hen bird"],
  ["🐧", "penguin", "Animals", "bird antarctic"],
  ["🐦", "bird", "Animals", "tweet"],
  ["🦆", "duck", "Animals", "bird quack"],
  ["🦉", "owl", "Animals", "bird wise night"],
  ["🐝", "bee", "Animals", "honey buzz"],
  ["🐛", "bug", "Animals", "insect defect issue"],
  ["🐞", "lady_beetle", "Animals", "ladybug insect"],
  ["🦋", "butterfly", "Animals", "insect change"],
  ["🐢", "turtle", "Animals", "slow tortoise"],
  ["🐍", "snake", "Animals", "python serpent"],
  ["🐙", "octopus", "Animals", "sea tentacles"],
  ["🐳", "whale", "Animals", "sea docker ocean"],
  ["🐬", "dolphin", "Animals", "sea ocean"],
  ["🐟", "fish", "Animals", "sea ocean"],
  ["🦄", "unicorn", "Animals", "magic fantasy"],
  ["🐴", "horse", "Animals", "pony"],
  ["🐺", "wolf", "Animals", "howl"],
  ["🌵", "cactus", "Animals", "plant desert"],
  ["🌲", "evergreen_tree", "Animals", "forest pine"],
  ["🌳", "deciduous_tree", "Animals", "forest wood"],
  ["🌴", "palm_tree", "Animals", "beach tropical"],
  ["🌱", "seedling", "Animals", "plant grow sprout new"],
  ["🌿", "herb", "Animals", "plant leaf"],
  ["🍀", "four_leaf_clover", "Animals", "luck lucky"],
  ["🌺", "hibiscus", "Animals", "flower"],
  ["🌻", "sunflower", "Animals", "flower sun"],
  ["🌹", "rose", "Animals", "flower love"],
  ["🌸", "cherry_blossom", "Animals", "flower sakura spring"],
  ["🍎", "apple", "Food", "fruit red"],
  ["🍌", "banana", "Food", "fruit"],
  ["🍇", "grapes", "Food", "fruit wine"],
  ["🍓", "strawberry", "Food", "fruit berry"],
  ["🍑", "peach", "Food", "fruit"],
  ["🍉", "watermelon", "Food", "fruit summer"],
  ["🍋", "lemon", "Food", "fruit sour citrus"],
  ["🥑", "avocado", "Food", "toast fruit"],
  ["🍅", "tomato", "Food", "vegetable"],
  ["🥕", "carrot", "Food", "vegetable"],
  ["🌽", "corn", "Food", "vegetable maize"],
  ["🥔", "potato", "Food", "vegetable"],
  ["🍞", "bread", "Food", "loaf bakery"],
  ["🥐", "croissant", "Food", "bakery french"],
  ["🧀", "cheese", "Food", "dairy"],
  ["🍔", "hamburger", "Food", "burger fastfood"],
  ["🍟", "fries", "Food", "fastfood chips"],
  ["🍕", "pizza", "Food", "slice italian"],
  ["🌮", "taco", "Food", "mexican"],
  ["🌯", "burrito", "Food", "mexican wrap"],
  ["🍣", "sushi", "Food", "japanese fish"],
  ["🍜", "ramen", "Food", "noodles soup"],
  ["🍝", "spaghetti", "Food", "pasta italian"],
  ["🍚", "rice", "Food", "bowl"],
  ["🥗", "green_salad", "Food", "healthy vegetables"],
  ["🍳", "fried_egg", "Food", "breakfast cooking"],
  ["🥞", "pancakes", "Food", "breakfast syrup"],
  ["🍰", "cake", "Food", "dessert slice"],
  ["🎂", "birthday", "Food", "cake celebrate party"],
  ["🍪", "cookie", "Food", "dessert biscuit"],
  ["🍩", "doughnut", "Food", "dessert donut"],
  ["🍫", "chocolate_bar", "Food", "dessert sweet"],
  ["🍿", "popcorn", "Food", "movie snack"],
  ["🍺", "beer", "Food", "drink pub"],
  ["🍷", "wine_glass", "Food", "drink red"],
  ["🍸", "cocktail", "Food", "drink martini"],
  ["🥂", "champagne_glasses", "Food", "cheers celebrate toast"],
  ["☕", "coffee", "Food", "drink espresso caffeine"],
  ["🍵", "tea", "Food", "drink green"],
  ["🧊", "ice_cube", "Food", "cold frozen"],
  ["⚽", "soccer", "Activity", "football sport ball"],
  ["🏀", "basketball", "Activity", "sport ball"],
  ["🏈", "football", "Activity", "sport nfl"],
  ["🎾", "tennis", "Activity", "sport ball"],
  ["🏐", "volleyball", "Activity", "sport ball"],
  ["🏓", "ping_pong", "Activity", "table tennis sport"],
  ["🏸", "badminton", "Activity", "sport"],
  ["🥅", "goal", "Activity", "net sport target"],
  ["🎯", "dart", "Activity", "target bullseye goal aim focus"],
  ["🎲", "game_die", "Activity", "dice random luck"],
  ["🎮", "video_game", "Activity", "controller gaming play"],
  ["🕹️", "joystick", "Activity", "arcade gaming"],
  ["🎸", "guitar", "Activity", "music rock"],
  ["🎹", "musical_keyboard", "Activity", "piano music"],
  ["🎤", "microphone", "Activity", "sing podcast audio"],
  ["🎧", "headphones", "Activity", "music audio listen"],
  ["🎬", "clapper", "Activity", "movie film action video"],
  ["🎨", "art", "Activity", "palette paint design"],
  ["🏆", "trophy", "Activity", "win award champion"],
  ["🥇", "first_place", "Activity", "gold medal win"],
  ["🥈", "second_place", "Activity", "silver medal"],
  ["🥉", "third_place", "Activity", "bronze medal"],
  ["🎉", "tada", "Activity", "party celebrate hooray launch"],
  ["🎊", "confetti_ball", "Activity", "party celebrate"],
  ["🎁", "gift", "Activity", "present birthday"],
  ["🚗", "car", "Travel", "drive automobile"],
  ["🚕", "taxi", "Travel", "cab"],
  ["🚌", "bus", "Travel", "transit"],
  ["🚑", "ambulance", "Travel", "emergency hospital"],
  ["🚒", "fire_engine", "Travel", "emergency"],
  ["🚲", "bike", "Travel", "bicycle cycle"],
  ["🛴", "kick_scooter", "Travel", "scooter"],
  ["✈️", "airplane", "Travel", "flight fly travel"],
  ["🚀", "rocket", "Travel", "launch ship deploy fast"],
  ["🛸", "flying_saucer", "Travel", "ufo alien"],
  ["🚁", "helicopter", "Travel", "fly"],
  ["⛵", "sailboat", "Travel", "boat sea"],
  ["🚢", "ship", "Travel", "boat cruise"],
  ["🚂", "steam_locomotive", "Travel", "train rail"],
  ["🗺️", "world_map", "Travel", "atlas geography"],
  ["🗽", "statue_of_liberty", "Travel", "new york usa"],
  ["🏔️", "mountain", "Travel", "peak snow"],
  ["🏝️", "desert_island", "Travel", "beach vacation"],
  ["🏠", "house", "Travel", "home building"],
  ["🏢", "office", "Travel", "building work"],
  ["🏥", "hospital", "Travel", "medical"],
  ["🏦", "bank", "Travel", "money building"],
  ["🌍", "earth_africa", "Travel", "world globe planet"],
  ["🌎", "earth_americas", "Travel", "world globe planet"],
  ["🌏", "earth_asia", "Travel", "world globe planet"],
  ["🌙", "crescent_moon", "Travel", "night dark sleep"],
  ["☀️", "sunny", "Travel", "sun weather clear"],
  ["⭐", "star", "Travel", "favorite rating"],
  ["🌟", "star2", "Travel", "glowing sparkle special"],
  ["✨", "sparkles", "Travel", "shiny magic new clean"],
  ["⚡", "zap", "Travel", "lightning fast power"],
  ["🔥", "fire", "Travel", "hot flame lit burn"],
  ["❄️", "snowflake", "Travel", "cold winter freeze"],
  ["🌈", "rainbow", "Travel", "colors pride"],
  ["☁️", "cloud", "Travel", "weather sky"],
  ["🌧️", "cloud_rain", "Travel", "weather rainy"],
  ["💧", "droplet", "Travel", "water drop"],
  ["🌊", "ocean", "Travel", "wave water sea"],
  ["💻", "computer", "Objects", "laptop macbook work code"],
  ["🖥️", "desktop_computer", "Objects", "monitor screen"],
  ["⌨️", "keyboard", "Objects", "typing input"],
  ["🖱️", "computer_mouse", "Objects", "click pointer"],
  ["🖨️", "printer", "Objects", "print paper"],
  ["📱", "iphone", "Objects", "phone mobile smartphone"],
  ["☎️", "telephone", "Objects", "call phone"],
  ["📷", "camera", "Objects", "photo picture"],
  ["📹", "video_camera", "Objects", "record film"],
  ["🎥", "movie_camera", "Objects", "film record"],
  ["📺", "tv", "Objects", "television screen"],
  ["📻", "radio", "Objects", "broadcast audio"],
  ["⏰", "alarm_clock", "Objects", "time wake reminder"],
  ["⌛", "hourglass", "Objects", "time wait pending"],
  ["⏳", "hourglass_flowing_sand", "Objects", "time wait loading"],
  ["🔋", "battery", "Objects", "power charge"],
  ["🔌", "electric_plug", "Objects", "power connect"],
  ["💡", "bulb", "Objects", "idea light insight"],
  ["🔦", "flashlight", "Objects", "torch light"],
  ["🔍", "mag", "Objects", "search find zoom look"],
  ["🔎", "mag_right", "Objects", "search find zoom"],
  ["🔐", "closed_lock_with_key", "Objects", "secure auth password"],
  ["🔒", "lock", "Objects", "secure private closed"],
  ["🔓", "unlock", "Objects", "open public"],
  ["🔑", "key", "Objects", "password access secret"],
  ["🔨", "hammer", "Objects", "build tool fix"],
  ["🛠️", "hammer_and_wrench", "Objects", "tools build maintenance"],
  ["🔧", "wrench", "Objects", "tool fix config"],
  ["⚙️", "gear", "Objects", "settings config cog"],
  ["🧲", "magnet", "Objects", "attract"],
  ["🧪", "test_tube", "Objects", "experiment lab science"],
  ["🧬", "dna", "Objects", "genetics biology"],
  ["💊", "pill", "Objects", "medicine health"],
  ["🩹", "adhesive_bandage", "Objects", "bandaid patch fix"],
  ["🚪", "door", "Objects", "entry exit"],
  ["🪑", "chair", "Objects", "seat furniture"],
  ["🛏️", "bed", "Objects", "sleep rest"],
  ["🧹", "broom", "Objects", "clean sweep cleanup"],
  ["🗑️", "wastebasket", "Objects", "trash delete bin remove"],
  ["📦", "package", "Objects", "box shipping bundle release"],
  ["📫", "mailbox", "Objects", "post mail"],
  ["✉️", "envelope", "Objects", "mail email letter"],
  ["📝", "memo", "Objects", "note write edit document"],
  ["📄", "page_facing_up", "Objects", "document file paper"],
  ["📋", "clipboard", "Objects", "copy paste list"],
  ["📊", "bar_chart", "Objects", "graph analytics data"],
  ["📈", "chart_increasing", "Objects", "growth up trend metrics"],
  ["📉", "chart_decreasing", "Objects", "down decline loss"],
  ["📅", "date", "Objects", "calendar schedule"],
  ["📆", "calendar", "Objects", "date schedule"],
  ["📌", "pushpin", "Objects", "pin location mark"],
  ["📎", "paperclip", "Objects", "attach file"],
  ["🔗", "link", "Objects", "chain url reference"],
  ["📚", "books", "Objects", "library read docs"],
  ["📖", "open_book", "Objects", "read docs guide"],
  ["🔖", "bookmark", "Objects", "save mark tag"],
  ["🏷️", "label", "Objects", "tag category"],
  ["💰", "moneybag", "Objects", "cash budget rich"],
  ["💳", "credit_card", "Objects", "payment billing"],
  ["💎", "gem", "Objects", "diamond jewel valuable"],
  ["⚖️", "balance_scale", "Objects", "justice fair legal"],
  ["🧭", "compass", "Objects", "direction navigate"],
  ["🔔", "bell", "Objects", "notification alert ring"],
  ["🔕", "no_bell", "Objects", "mute silence"],
  ["📢", "loudspeaker", "Objects", "announce broadcast"],
  ["🧩", "puzzle_piece", "Objects", "plugin extension fit"],
  ["🪄", "magic_wand", "Objects", "magic auto transform"],
  ["❤️", "heart", "Symbols", "love red like"],
  ["🧡", "orange_heart", "Symbols", "love"],
  ["💛", "yellow_heart", "Symbols", "love"],
  ["💚", "green_heart", "Symbols", "love"],
  ["💙", "blue_heart", "Symbols", "love"],
  ["💜", "purple_heart", "Symbols", "love"],
  ["🖤", "black_heart", "Symbols", "love dark"],
  ["💔", "broken_heart", "Symbols", "sad breakup"],
  ["💯", "100", "Symbols", "perfect score hundred"],
  ["✅", "white_check_mark", "Symbols", "done complete yes pass"],
  ["☑️", "ballot_box_with_check", "Symbols", "done checkbox"],
  ["✔️", "heavy_check_mark", "Symbols", "done tick yes"],
  ["❌", "x", "Symbols", "no wrong fail cancel"],
  ["❎", "negative_squared_cross_mark", "Symbols", "no reject"],
  ["⚠️", "warning", "Symbols", "caution alert danger"],
  ["🚫", "no_entry_sign", "Symbols", "forbidden banned stop"],
  ["⛔", "no_entry", "Symbols", "stop blocked"],
  ["❓", "question", "Symbols", "help unknown ask"],
  ["❗", "exclamation", "Symbols", "important alert"],
  ["‼️", "bangbang", "Symbols", "urgent important"],
  ["🔴", "red_circle", "Symbols", "stop record error"],
  ["🟠", "orange_circle", "Symbols", "warn"],
  ["🟡", "yellow_circle", "Symbols", "caution"],
  ["🟢", "green_circle", "Symbols", "go ok healthy"],
  ["🔵", "blue_circle", "Symbols", "info"],
  ["⚫", "black_circle", "Symbols", "dot"],
  ["⚪", "white_circle", "Symbols", "dot empty"],
  ["🔺", "small_red_triangle", "Symbols", "up increase"],
  ["🔻", "small_red_triangle_down", "Symbols", "down decrease"],
  ["🔶", "large_orange_diamond", "Symbols", "shape"],
  ["♻️", "recycle", "Symbols", "reuse green refactor"],
  ["🔁", "repeat", "Symbols", "loop again retry"],
  ["🔄", "arrows_counterclockwise", "Symbols", "refresh sync reload"],
  ["➡️", "arrow_right", "Symbols", "next forward"],
  ["⬅️", "arrow_left", "Symbols", "back previous"],
  ["⬆️", "arrow_up", "Symbols", "top increase"],
  ["⬇️", "arrow_down", "Symbols", "bottom decrease"],
  ["▶️", "arrow_forward", "Symbols", "play start run"],
  ["⏸️", "pause_button", "Symbols", "hold wait"],
  ["⏹️", "stop_button", "Symbols", "halt end"],
  ["🆕", "new", "Symbols", "fresh badge"],
  ["🆗", "ok", "Symbols", "fine approve"],
  ["🆙", "up", "Symbols", "upgrade level"],
  ["🔝", "top", "Symbols", "best up"],
  ["🈹", "u5272", "Symbols", "discount"],
  ["©️", "copyright", "Symbols", "legal"],
  ["®️", "registered", "Symbols", "trademark legal"],
  ["™️", "tm", "Symbols", "trademark"],
  ["💤", "zzz", "Symbols", "sleep tired idle"],
  ["💬", "speech_balloon", "Symbols", "comment chat message"],
  ["💭", "thought_balloon", "Symbols", "thinking idea"],
  ["🗯️", "right_anger_bubble", "Symbols", "shout rant"],
  ["🔊", "loud_sound", "Symbols", "volume audio"],
  ["🔇", "mute", "Symbols", "silence volume off"],
];

export const emojiEntries: readonly EmojiEntry[] = EMOJI_TABLE.map(
  ([char, shortcode, group, keywords]) => ({
    char,
    shortcode,
    name: shortcode.replace(/_/g, " "),
    group,
    keywords: keywords.split(" "),
  }),
);
