import { existsSync, readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { GLYPH_GRIDS, GLYPH_NAMES } from "./catalog";
import { ANIMATED_GLYPH_SOURCES, type Cut, type PartSource } from "./parts";
import { splitSubpaths } from "./path";

const ICONS_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_DIR = join(ICONS_DIR, "../..");
const FLUENT_DIR = join(dirname(fileURLToPath(import.meta.resolve("@fluentui/svg-icons/package.json"))), "icons");
const ANIMATED_GRID = 24;
const BOX = "M-2 -2H26V26H-2Z";

const SVG_PATTERN = /^<svg [^>]*viewBox="0 0 (\d+) (\d+)"[^>]*>(.*)<\/svg>\s*$/s;
const PATH_PATTERN = /<path d="([^"]+)"\s*\/>/g;

const HEADER = [
  "// Generated by shared/icons/generate.ts from @fluentui/svg-icons (MIT).",
  "// Do not edit; run `bun shared/icons/generate.ts` after changing the catalog or parts.",
  "",
].join("\n");

function fluentFile(name: string, grid: number): string {
  const filled = name.endsWith("_filled");
  const base = filled ? name.slice(0, -"_filled".length) : name;
  return join(FLUENT_DIR, `${base}_${grid}_${filled ? "filled" : "regular"}.svg`);
}

/** Reads a Fluent SVG and returns its path data, refusing anything but plain paths. */
function readGlyph(name: string, grid: number): string | undefined {
  const file = fluentFile(name, grid);
  if (!existsSync(file)) return undefined;
  const svg = readFileSync(file, "utf8");
  const match = SVG_PATTERN.exec(svg);
  if (!match || Number(match[1]) !== grid || Number(match[2]) !== grid) {
    throw new Error(`${relative(REPO_DIR, file)}: expected a ${grid}×${grid} view box`);
  }
  const body = match[3]!;
  const paths = [...body.matchAll(PATH_PATTERN)].map((path) => path[1]!);
  if (paths.length === 0 || body.replace(PATH_PATTERN, "").trim() !== "") {
    throw new Error(`${relative(REPO_DIR, file)}: contains elements other than <path d>`);
  }
  return paths.join("");
}

function renderGlyphs(): string {
  const lines = [HEADER, 'import type { GlyphName } from "../catalog";', ""];
  lines.push("/** Path data per glyph and grid. A glyph Fluent draws on one grid only has one entry. */");
  lines.push("export const GLYPHS: Record<GlyphName, { readonly 20?: string; readonly 24?: string }> = {");
  for (const name of GLYPH_NAMES) {
    const entries = GLYPH_GRIDS.flatMap((grid) => {
      const d = readGlyph(name, grid);
      return d === undefined ? [] : [`${grid}: ${JSON.stringify(d)}`];
    });
    if (entries.length === 0) {
      throw new Error(`Fluent has no regular ${GLYPH_GRIDS.join(" or ")} glyph named "${name}"`);
    }
    lines.push(`  ${name}: { ${entries.join(", ")} },`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

type ResolvedClip = { d: string; rule: "nonzero" | "evenodd" };

function resolveCut(cut: Cut): ResolvedClip {
  return cut.outside ? { d: BOX + cut.d, rule: "evenodd" } : { d: cut.d, rule: "nonzero" };
}

function pick(subpaths: readonly string[], indices: readonly number[], owner: string): string {
  return indices
    .map((index) => {
      const subpath = subpaths[index];
      if (subpath === undefined) throw new Error(`${owner}: glyph has no subpath ${index}`);
      return subpath;
    })
    .join("");
}

function resolvePart(icon: string, subpaths: readonly string[], part: PartSource) {
  const owner = `${icon}.${part.id}`;
  if ((part.subpaths === undefined) === (part.d === undefined)) {
    throw new Error(`${owner}: give either subpaths or d`);
  }
  const resolved: Record<string, unknown> = {
    id: part.id,
    d: part.d ?? pick(subpaths, part.subpaths!, owner),
  };
  if (part.clip) resolved.clip = resolveCut(part.clip);
  if (part.window) {
    resolved.window =
      "subpaths" in part.window
        ? { d: pick(subpaths, part.window.subpaths, owner), rule: "nonzero" }
        : resolveCut(part.window);
  }
  if (part.within) resolved.within = part.within;
  if (part.occluder) {
    resolved.occluder = { follows: part.occluder.follows, d: pick(subpaths, part.occluder.subpaths, owner) };
  }
  if (part.hidden) resolved.hidden = part.hidden;
  return resolved;
}

function renderAnimated(): string {
  const lines = [
    HEADER,
    'import type { AnimatedGeometry } from "../geometry";',
    'import type { AnimatedIconId } from "../parts";',
    "",
    "/** Each animated icon's glyph split into the parts its motion moves, on the 24-unit grid. */",
    "export const ANIMATED_GEOMETRY: Record<AnimatedIconId, AnimatedGeometry> = {",
  ];
  for (const [icon, source] of Object.entries(ANIMATED_GLYPH_SOURCES)) {
    const d = readGlyph(source.glyph, ANIMATED_GRID);
    if (d === undefined) throw new Error(`${icon}: Fluent has no 24-unit "${source.glyph}"`);
    const subpaths = splitSubpaths(d);
    const parts = source.parts.map((part: PartSource) => resolvePart(icon, subpaths, part));
    lines.push(`  ${icon}: {`);
    lines.push(`    glyph: ${JSON.stringify(source.glyph)},`);
    lines.push("    parts: [");
    for (const part of parts) lines.push(`      ${JSON.stringify(part)},`);
    lines.push("    ],");
    lines.push("  },");
  }
  lines.push("};", "");
  return lines.join("\n");
}

/** The generated files, keyed by path, as `generate.ts` writes them. */
export function renderIconData(): ReadonlyMap<string, string> {
  return new Map([
    [join(ICONS_DIR, "generated/glyphs.ts"), renderGlyphs()],
    [join(ICONS_DIR, "generated/animated.ts"), renderAnimated()],
  ]);
}
