[package]
name = "skriuw-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json.workspace = true
skriuw-domain = { path = "../skriuw-domain" }
skriuw-sqlite = { path = "../skriuw-sqlite" }
skriuw-storage = { path = "../skriuw-storage" }
uuid.workspace = true
