import type { Block } from "@blocknote/core";
import type {
  StorageAdapter,
  StorageInfo,
  StorageOperation,
  StorageOperationResult,
  StorageEvent,
  StorageEventListener,
  StorageCapabilities,
} from "../types";
import type { Note, Folder, Item, CreateNoteData, UpdateNoteData, CreateFolderData } from "@/features/notes/types";
import { getElectricConfig } from "../electric/config";
import { ElectricDatabase, electrify } from "electric-sql/wa-sqlite";
// Electric type will be available from the generated client
// For now, using any to avoid type errors until client is generated
type Electric = any;
import { setElectricInstance } from "../hooks/useElectricStorage";

// Import generated schema (will be available after running electric-sql generate)
import { schema } from "../electric/generated/client";

class StorageError extends Error {
  constructor(message: string, cause?: unknown) {
    super(message);
    this.name = 'StorageError';
    this.cause = cause;
  }
}

export class ElectricSQLAdapter implements StorageAdapter {
  readonly name = "electric";
  readonly type = 'hybrid' as const;

  private electric: Electric | null = null;
  private db: any = null; // Will be typed with generated client
  private listeners: StorageEventListener[] = [];
  private currentUserId: string | null = null;
  private initialized = false;

  constructor(private options?: Record<string, unknown>) { }

  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    try {
      const config = getElectricConfig();

      // Initialize local SQLite database
      const conn = await ElectricDatabase.init('quantum-works.db');

      // Check if schema is available (will be generated by electric-sql generate)
      if (!schema || Object.keys(schema).length === 0) {
        console.warn('ElectricSQL schema not generated yet. Run: pnpm electric:generate');
        console.warn('For now, using placeholder schema. Some features may not work.');
        // Continue with initialization but mark as not fully initialized
        this.initialized = false;
        return;
      }

      const electric = await electrify(conn, schema, {
        url: config.url,
        debug: config.debug,
      });

      await electric.connect(config.authToken);

      this.electric = electric;
      this.db = electric.db;

      // Set global instance for React hooks
      setElectricInstance(electric);

      // Create or get anonymous user
      this.currentUserId = await this.getOrCreateAnonymousUser();

      // Set up shapes for syncing
      await this.setupShapes();

      this.initialized = true;
    } catch (error) {
      throw new StorageError('Failed to initialize ElectricSQL adapter', error);
    }
  }

  async destroy(): Promise<void> {
    this.listeners = [];
    if (this.electric) {
      // await this.electric.close();
      this.electric = null;
      setElectricInstance(null);
    }
    this.db = null;
    this.currentUserId = null;
    this.initialized = false;
  }

  // Getter for Electric instance (for use in providers)
  getElectric(): Electric | null {
    return this.electric;
  }

  async isHealthy(): Promise<boolean> {
    if (!this.initialized || !this.electric) {
      return false;
    }
    // Check connection status
    // return this.electric.isConnected();
    return true; // Placeholder
  }

  async getStorageInfo(): Promise<StorageInfo> {
    const items = await this.getItems();

    return {
      adapter: this.name,
      type: this.type,
      totalItems: items.length,
      isOnline: navigator.onLine,
      capabilities: {
        realtime: true,
        offline: true,
        sync: true,
        backup: false,
        versioning: false,
        collaboration: true,
      },
    };
  }

  async getItems(): Promise<Item[]> {
    if (!this.db || !this.currentUserId || !this.db.folders || !this.db.notes) {
      return [];
    }

    try {
      // Fetch root folders and notes (where parentId is null)
      const folders = await this.db.folders.findMany({
        where: {
          userId: this.currentUserId,
          parentId: null,
        },
      });

      const notes = await this.db.notes.findMany({
        where: {
          userId: this.currentUserId,
          folderId: null,
        },
      });

      // Build hierarchical structure
      return await this.buildItemHierarchy(folders, notes);
    } catch (error) {
      throw new StorageError('Failed to get items', error);
    }
  }

  async findItemById(id: string): Promise<Item | undefined> {
    if (!this.db || !this.db.notes || !this.db.folders) {
      return undefined;
    }

    try {
      // Try to find as note first
      const note = await this.db.notes.findUnique({
        where: { id },
      });
      if (note && note.userId === this.currentUserId) {
        return this.mapNoteToItem(note);
      }

      // Try to find as folder
      const folder = await this.db.folders.findUnique({
        where: { id },
      });
      if (folder && folder.userId === this.currentUserId) {
        return await this.mapFolderToItem(folder);
      }

      return undefined;
    } catch (error) {
      throw new StorageError(`Failed to find item ${id}`, error);
    }
  }

  async findNote(id: string): Promise<Note | undefined> {
    if (!this.db || !this.db.notes) {
      return undefined;
    }

    try {
      const note = await this.db.notes.findUnique({
        where: { id },
      });
      if (note && note.userId === this.currentUserId) {
        return this.mapNoteToItem(note) as Note;
      }
      return undefined;
    } catch (error) {
      throw new StorageError(`Failed to find note ${id}`, error);
    }
  }

  async createNote(data: CreateNoteData): Promise<Note> {
    if (!this.db || !this.currentUserId) {
      throw new StorageError('Database not initialized');
    }

    try {
      const now = Date.now();
      const noteData = {
        id: `note-${now}`,
        name: data.name,
        content: data.content || [],
        userId: this.currentUserId,
        folderId: data.parentFolderId || null,
        createdAt: new Date(now),
        updatedAt: new Date(now),
      };

      if (!this.db.notes) {
        throw new StorageError('Notes table not available');
      }

      const note = await this.db.notes.create({
        data: noteData,
      });

      const mappedNote = this.mapNoteToItem(note) as Note;
      this.emit({ type: 'created', itemType: 'note', itemId: mappedNote.id, data: mappedNote });
      return mappedNote;
    } catch (error) {
      throw new StorageError('Failed to create note', error);
    }
  }

  async createFolder(data: CreateFolderData): Promise<Folder> {
    if (!this.db || !this.currentUserId) {
      throw new StorageError('Database not initialized');
    }

    try {
      const now = Date.now();
      const folderData = {
        id: `folder-${now}`,
        name: data.name,
        userId: this.currentUserId,
        parentId: data.parentFolderId || null,
        createdAt: new Date(now),
        updatedAt: new Date(now),
      };

      if (!this.db.folders) {
        throw new StorageError('Folders table not available');
      }

      const folder = await this.db.folders.create({
        data: folderData,
      });

      const mappedFolder = await this.mapFolderToItem(folder);
      this.emit({ type: 'created', itemType: 'folder', itemId: mappedFolder.id, data: mappedFolder });
      return mappedFolder;
    } catch (error) {
      throw new StorageError('Failed to create folder', error);
    }
  }

  async updateNote(id: string, data: UpdateNoteData): Promise<Note | undefined> {
    if (!this.db || !this.currentUserId) {
      return undefined;
    }

    try {
      if (!this.db.notes) {
        return undefined;
      }

      const note = await this.db.notes.findUnique({
        where: { id },
      });

      if (!note || note.userId !== this.currentUserId) {
        return undefined;
      }

      const updateData: any = {
        updatedAt: new Date(),
      };
      if (data.name !== undefined) updateData.name = data.name;
      if (data.content !== undefined) updateData.content = data.content;

      const updated = await this.db.notes.update({
        where: { id },
        data: updateData,
      });

      const mappedNote = this.mapNoteToItem(updated) as Note;
      this.emit({ type: 'updated', itemType: 'note', itemId: id, data: mappedNote });
      return mappedNote;
    } catch (error) {
      throw new StorageError(`Failed to update note ${id}`, error);
    }
  }

  async renameItem(id: string, newName: string): Promise<Item | undefined> {
    if (!this.db || !this.currentUserId) {
      return undefined;
    }

    try {
      if (!this.db.notes || !this.db.folders) {
        return undefined;
      }

      // Try note first
      const note = await this.db.notes.findUnique({ where: { id } });
      if (note && note.userId === this.currentUserId) {
        const updated = await this.db.notes.update({
          where: { id },
          data: { name: newName, updatedAt: new Date() },
        });
        const mapped = this.mapNoteToItem(updated) as Note;
        this.emit({ type: 'updated', itemType: 'note', itemId: id, data: mapped });
        return mapped;
      }

      // Try folder
      const folder = await this.db.folders.findUnique({ where: { id } });
      if (folder && folder.userId === this.currentUserId) {
        const updated = await this.db.folders.update({
          where: { id },
          data: { name: newName, updatedAt: new Date() },
        });
        const mapped = await this.mapFolderToItem(updated);
        this.emit({ type: 'updated', itemType: 'folder', itemId: id, data: mapped });
        return mapped;
      }

      return undefined;
    } catch (error) {
      throw new StorageError(`Failed to rename item ${id}`, error);
    }
  }

  async deleteItem(id: string): Promise<boolean> {
    if (!this.db || !this.currentUserId) {
      return false;
    }

    try {
      if (!this.db.notes || !this.db.folders) {
        return false;
      }

      // Try note first
      const note = await this.db.notes.findUnique({ where: { id } });
      if (note && note.userId === this.currentUserId) {
        await this.db.notes.delete({ where: { id } });
        this.emit({ type: 'deleted', itemType: 'note', itemId: id });
        return true;
      }

      // Try folder
      const folder = await this.db.folders.findUnique({ where: { id } });
      if (folder && folder.userId === this.currentUserId) {
        await this.db.folders.delete({ where: { id } });
        this.emit({ type: 'deleted', itemType: 'folder', itemId: id });
        return true;
      }

      return false;
    } catch (error) {
      throw new StorageError(`Failed to delete item ${id}`, error);
    }
  }

  async moveItem(itemId: string, targetFolderId: string | null): Promise<boolean> {
    if (!this.db || !this.currentUserId) {
      return false;
    }

    try {
      if (!this.db.notes || !this.db.folders) {
        return false;
      }

      // Try note first
      const note = await this.db.notes.findUnique({ where: { id: itemId } });
      if (note && note.userId === this.currentUserId) {
        await this.db.notes.update({
          where: { id: itemId },
          data: { folderId: targetFolderId, updatedAt: new Date() },
        });
        this.emit({ type: 'moved', itemType: 'note', itemId });
        return true;
      }

      // Try folder
      const folder = await this.db.folders.findUnique({ where: { id: itemId } });
      if (folder && folder.userId === this.currentUserId) {
        await this.db.folders.update({
          where: { id: itemId },
          data: { parentId: targetFolderId, updatedAt: new Date() },
        });
        this.emit({ type: 'moved', itemType: 'folder', itemId });
        return true;
      }

      return false;
    } catch (error) {
      throw new StorageError(`Failed to move item ${itemId}`, error);
    }
  }

  async countChildren(folderId: string): Promise<number> {
    if (!this.db || !this.currentUserId) {
      return 0;
    }

    try {
      if (!this.db.folders) {
        return 0;
      }

      const folder = await this.db.folders.findUnique({
        where: { id: folderId },
        include: {
          children: true,
          notes: true,
        },
      });

      if (!folder || folder.userId !== this.currentUserId) {
        return 0;
      }

      return (folder.children?.length || 0) + (folder.notes?.length || 0);
    } catch (error) {
      throw new StorageError(`Failed to count children for folder ${folderId}`, error);
    }
  }

  async batchUpdate(operations: StorageOperation[]): Promise<StorageOperationResult[]> {
    const results: StorageOperationResult[] = [];

    for (const operation of operations) {
      try {
        let result: any;

        switch (operation.type) {
          case 'create_note':
            result = await this.createNote(operation.data);
            break;
          case 'create_folder':
            result = await this.createFolder(operation.data);
            break;
          case 'update_note':
            result = await this.updateNote(operation.id, operation.data);
            break;
          case 'rename_item':
            result = await this.renameItem(operation.id, operation.newName);
            break;
          case 'delete_item':
            result = await this.deleteItem(operation.id);
            break;
          case 'move_item':
            result = await this.moveItem(operation.itemId, operation.targetFolderId);
            break;
        }

        results.push({
          operation,
          success: true,
          data: result,
        });
      } catch (error) {
        results.push({
          operation,
          success: false,
          error: error instanceof Error ? error.message : 'Unknown error',
        });
      }
    }

    return results;
  }

  // Event management
  addEventListener(listener: StorageEventListener): void {
    this.listeners.push(listener);
  }

  removeEventListener(listener: StorageEventListener): void {
    const index = this.listeners.indexOf(listener);
    if (index > -1) {
      this.listeners.splice(index, 1);
    }
  }

  private emit(event: StorageEvent): void {
    this.listeners.forEach(listener => {
      try {
        listener(event);
      } catch (error) {
        console.error('Error in storage event listener:', error);
      }
    });
  }

  // Helper methods
  private async getOrCreateAnonymousUser(): Promise<string> {
    // Generate or retrieve anonymous user ID
    // This could be stored in localStorage or generated per session
    let userId = localStorage.getItem('electric_user_id');
    if (!userId) {
      // Create new anonymous user
      if (this.db && this.db.users) {
        const user = await this.db.users.create({
          data: {
            identifier: `anon-${Date.now()}`,
          },
        });
        userId = user.id;
        localStorage.setItem('electric_user_id', userId);
      } else {
        // Fallback: generate temporary ID until schema is ready
        userId = `anon-${Date.now()}`;
        localStorage.setItem('electric_user_id', userId);
      }
    }
    return userId;
  }

  private async setupShapes(): Promise<void> {
    if (!this.db || !this.currentUserId) {
      return;
    }

    // Set up sync shapes for notes and folders
    if (this.db.notes) {
      await this.db.notes.sync({
        where: {
          userId: this.currentUserId,
        },
      });
    }

    if (this.db.folders) {
      await this.db.folders.sync({
        where: {
          userId: this.currentUserId,
        },
      });
    }
  }

  private mapNoteToItem(note: any): Note {
    return {
      id: note.id,
      name: note.name,
      content: note.content as Block[],
      createdAt: note.createdAt.getTime(),
      updatedAt: note.updatedAt.getTime(),
      type: 'note',
    };
  }

  private async mapFolderToItem(folder: any): Promise<Folder> {
    // Fetch children recursively
    let children: Item[] = [];

    if (this.db && this.db.folders && this.db.notes) {
      const childrenFolders = await this.db.folders.findMany({
        where: {
          parentId: folder.id,
          userId: this.currentUserId,
        },
      });

      const childrenNotes = await this.db.notes.findMany({
        where: {
          folderId: folder.id,
          userId: this.currentUserId,
        },
      });

      children = [
        ...(await Promise.all(childrenFolders.map(f => this.mapFolderToItem(f)))),
        ...childrenNotes.map(n => this.mapNoteToItem(n)),
      ];
    }

    return {
      id: folder.id,
      name: folder.name,
      type: 'folder',
      children,
      createdAt: folder.createdAt.getTime(),
      updatedAt: folder.updatedAt.getTime(),
    };
  }

  private async buildItemHierarchy(folders: any[], notes: any[]): Promise<Item[]> {
    // Build hierarchical structure from flat arrays
    const items: Item[] = [];

    // Add root folders (with their children populated)
    const folderItems = await Promise.all(folders.map(f => this.mapFolderToItem(f)));
    items.push(...folderItems);

    // Add root notes
    const noteItems = notes.map(n => this.mapNoteToItem(n));
    items.push(...noteItems);

    return items;
  }
}

