import { StyleSheet } from "react-native";

export const palette = {
  canvas: "#f6f2ea",
  canvasMuted: "#f0e7da",
  canvasStrong: "#efe8db",
  surface: "#fbf7f1",
  surfaceRaised: "#fffdf9",
  border: "#eadfce",
  text: "#201914",
  textMuted: "#6a5a4b",
  textSoft: "#8b7764",
  accent: "#bc5b2c",
  accentDeep: "#8c3f18",
  accentSoft: "#f3d3bf",
  accentWash: "#f7e6d8",
  danger: "#b24b43",
  dangerSoft: "#f6e0dc",
  success: "#396a55",
  shadow: "rgba(56, 31, 15, 0.08)",
} as const;

export const commonStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.canvas,
  },
  scrollContent: {
    padding: 20,
    gap: 18,
    paddingBottom: 36,
  },
  screenContent: {
    padding: 20,
    gap: 18,
  },
  card: {
    backgroundColor: palette.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 18,
    gap: 12,
    shadowColor: "#381f0f",
    shadowOpacity: 0.05,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    elevation: 2,
  },
  heroCard: {
    backgroundColor: palette.surfaceRaised,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 22,
    gap: 14,
    overflow: "hidden",
    shadowColor: "#381f0f",
    shadowOpacity: 0.09,
    shadowRadius: 28,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 3,
  },
  heroGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: palette.accentWash,
    top: -52,
    right: -48,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    color: palette.accent,
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700",
    color: palette.text,
  },
  headline: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
    color: palette.text,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: palette.textMuted,
  },
  caption: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.textSoft,
  },
  button: {
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.accent,
  },
  buttonSmall: {
    minHeight: 38,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.accent,
  },
  buttonSecondary: {
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.accentSoft,
  },
  buttonSecondarySmall: {
    minHeight: 38,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.accentWash,
  },
  buttonDanger: {
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.dangerSoft,
  },
  buttonLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#fff7ef",
  },
  buttonLabelSmall: {
    fontSize: 13,
    fontWeight: "700",
    color: "#fff7ef",
  },
  buttonLabelSecondary: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.accent,
  },
  buttonLabelSecondarySmall: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.accentDeep,
  },
  buttonLabelDanger: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.danger,
  },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#fffdfa",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: palette.text,
  },
  inputCompact: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#fffdfa",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: palette.text,
  },
  textArea: {
    minHeight: 180,
    textAlignVertical: "top",
  },
  row: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  rowWrap: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  rowBetween: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    justifyContent: "space-between",
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.accentSoft,
    alignSelf: "flex-start",
  },
  chipLabel: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "600",
  },
  chipMuted: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.canvasMuted,
    alignSelf: "flex-start",
  },
  chipMutedLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "700",
    color: palette.text,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  metricTile: {
    minWidth: 100,
    flexGrow: 1,
    backgroundColor: palette.canvasMuted,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 4,
  },
  metricValue: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: palette.text,
  },
  metricLabel: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: palette.textSoft,
    fontWeight: "700",
  },
  listCard: {
    backgroundColor: palette.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    gap: 10,
  },
  listTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "700",
    color: palette.text,
  },
  listSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: palette.textMuted,
  },
  divider: {
    height: 1,
    backgroundColor: palette.border,
  },
  moodPill: {
    minHeight: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceRaised,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  moodPillActive: {
    borderColor: palette.accent,
    backgroundColor: palette.accentSoft,
  },
  moodPillLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  moodPillLabelActive: {
    color: palette.accentDeep,
  },
});
