import { StyleSheet } from "react-native";

/**
 * Palette derived from the desktop web app's CSS custom properties.
 * All values are neutral greys (hsl 0 0% X%) with zero colour accent,
 * matching the monochromatic Haptic aesthetic.
 */
export const palette = {
  // Backgrounds — desktop: --background 0 0% 7%, --haptic-bg-deep 0 0% 5%
  canvas: "#121212",
  canvasMuted: "#171717",
  canvasStrong: "#0D0D0D",
  // Surfaces — desktop: --card 0 0% 9%, --popover 0 0% 11%
  surface: "#171717",
  surfaceRaised: "#1C1C1C",
  // Borders — desktop: --border 0 0% 18%, --haptic-divider 0 0% 15%
  border: "#2E2E2E",
  borderSubtle: "#262626",
  // Text — desktop: --foreground 0 0% 91%, --muted-foreground 0 0% 55%, --haptic-text-dim 0 0% 40%
  text: "#E8E8E8",
  textMuted: "#8C8C8C",
  textSoft: "#666666",
  // Accents — desktop uses white foreground as primary, --primary 0 0% 25%
  accent: "#404040",
  accentDeep: "#F2F2F2",
  accentSoft: "#1F1F1F",
  accentWash: "#1A1A1A",
  // Semantic
  danger: "#FF6B6B",
  dangerSoft: "#2A1313",
  success: "#66BB8A",
  successSoft: "#132A1E",
} as const;

/**
 * Border-radius scale matching the desktop.
 * Desktop base --radius is 0.375rem (6px).
 * Larger values (lg/xl) match the desktop's rounded-2xl (16px) used on
 * search panels, mobile sheets, and action-sheet groups.
 */
export const radius = {
  xs: 2,
  sm: 4,
  md: 6,
  lg: 10,
  xl: 16,
  full: 999,
} as const;

export const commonStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.canvas,
  },
  scrollContent: {
    padding: 20,
    gap: 18,
    paddingBottom: 36,
  },
  screenContent: {
    padding: 20,
    gap: 18,
  },
  card: {
    backgroundColor: palette.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 18,
    gap: 12,
  },
  heroCard: {
    backgroundColor: palette.surfaceRaised,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 22,
    gap: 14,
    overflow: "hidden",
  },
  heroGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: radius.full,
    backgroundColor: palette.accentWash,
    top: -52,
    right: -48,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    color: palette.textSoft,
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700",
    color: palette.text,
  },
  headline: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
    color: palette.text,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: palette.textMuted,
  },
  caption: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.textSoft,
  },
  button: {
    minHeight: 48,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.accent,
  },
  buttonSmall: {
    minHeight: 38,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.accent,
  },
  buttonSecondary: {
    minHeight: 48,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.accentSoft,
    borderWidth: 1,
    borderColor: palette.border,
  },
  buttonSecondarySmall: {
    minHeight: 38,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.accentWash,
    borderWidth: 1,
    borderColor: palette.borderSubtle,
  },
  buttonDanger: {
    minHeight: 48,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.dangerSoft,
  },
  buttonLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.text,
  },
  buttonLabelSmall: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.text,
  },
  buttonLabelSecondary: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.textMuted,
  },
  buttonLabelSecondarySmall: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.accentDeep,
  },
  buttonLabelDanger: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.danger,
  },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceRaised,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: palette.text,
  },
  inputCompact: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceRaised,
    borderRadius: radius.sm,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: palette.text,
  },
  textArea: {
    minHeight: 180,
    textAlignVertical: "top",
  },
  titleInput: {
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 4,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "700",
    color: palette.text,
  },
  noteBodyInput: {
    minHeight: 320,
    paddingHorizontal: 0,
    paddingTop: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 17,
    lineHeight: 27,
    color: palette.text,
    textAlignVertical: "top",
  },
  editorTopBar: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: palette.borderSubtle,
    backgroundColor: palette.canvas,
  },
  editorTopBarButton: {
    minHeight: 36,
    justifyContent: "center",
    paddingRight: 8,
  },
  editorTopBarButtonLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: palette.text,
  },
  editorTopBarMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  editorScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
    gap: 18,
  },
  editorHeaderBlock: {
    gap: 10,
  },
  editorEyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.textSoft,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  editorTitleInput: {
    paddingBottom: 8,
    fontSize: 36,
    lineHeight: 42,
  },
  editorMetaText: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.textMuted,
  },
  editorBodyInput: {
    minHeight: 420,
    fontSize: 18,
    lineHeight: 30,
    paddingBottom: 40,
  },
  row: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  rowWrap: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  rowBetween: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    justifyContent: "space-between",
  },
  chip: {
    borderRadius: radius.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: palette.accentSoft,
    alignSelf: "flex-start",
  },
  chipLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  chipMuted: {
    borderRadius: radius.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: palette.canvasMuted,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: palette.borderSubtle,
  },
  chipMutedLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "700",
    color: palette.text,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metricTile: {
    minWidth: 100,
    flexGrow: 1,
    backgroundColor: palette.canvasMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 4,
  },
  metricValue: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: palette.text,
  },
  metricLabel: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: palette.textSoft,
    fontWeight: "700",
  },
  listCard: {
    backgroundColor: palette.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    gap: 10,
  },
  listTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "700",
    color: palette.text,
  },
  listSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.textMuted,
  },
  listHeaderTitle: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "800",
    color: palette.text,
  },
  listHeaderMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.textSoft,
    fontWeight: "600",
  },
  noteRow: {
    backgroundColor: palette.surface,
    paddingHorizontal: 18,
    paddingVertical: 15,
    gap: 6,
  },
  noteSwipeShell: {
    overflow: "hidden",
    borderRadius: radius.md,
    backgroundColor: palette.surface,
  },
  noteRowPressed: {
    backgroundColor: palette.surfaceRaised,
  },
  noteRowBorder: {
    borderTopWidth: 1,
    borderTopColor: palette.borderSubtle,
  },
  noteMeta: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.textSoft,
    fontWeight: "600",
  },
  noteTitleRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
  },
  noteTitleCompact: {
    flex: 1,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "700",
    color: palette.text,
  },
  noteDateCompact: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.textSoft,
    fontWeight: "600",
  },
  notePreviewCompact: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.textMuted,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  brandLogo: {
    width: 44,
    height: 44,
    borderRadius: radius.md,
  },
  brandTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "800",
    color: palette.text,
  },
  brandSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.textSoft,
  },
  homeHeader: {
    gap: 14,
    paddingBottom: 2,
  },
  searchModeHeader: {
    gap: 4,
  },
  searchModeTitle: {
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "800",
    color: palette.text,
  },
  searchModeMeta: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.textMuted,
  },
  homeBrandCopy: {
    flex: 1,
    gap: 2,
  },
  homeSectionRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
  },
  homeSectionTitle: {
    flex: 1,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "800",
    color: palette.text,
  },
  homeSectionMeta: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: palette.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: radius.xl,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  iconButtonLabel: {
    fontSize: 22,
    lineHeight: 24,
    color: palette.text,
    fontWeight: "600",
  },
  searchShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.canvasMuted,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  searchShellActive: {
    backgroundColor: palette.surface,
  },
  searchLabel: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  searchCancelButton: {
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 12,
  },
  searchCancelButtonLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: palette.textMuted,
  },
  searchInput: {
    minHeight: 38,
    flex: 1,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 16,
    color: palette.text,
  },
  inlineAction: {
    minHeight: 30,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.canvasMuted,
    borderWidth: 1,
    borderColor: palette.border,
  },
  inlineActionLabel: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
    color: palette.textMuted,
  },
  sidebarGroup: {
    gap: 10,
  },
  sidebarGroupLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: palette.textSoft,
    paddingHorizontal: 4,
  },
  sidebarList: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    overflow: "hidden",
  },
  swipeActionTrack: {
    width: 112,
    paddingVertical: 6,
  },
  swipeActionTrackLeft: {
    paddingLeft: 6,
    paddingRight: 8,
  },
  swipeActionTrackRight: {
    paddingLeft: 8,
    paddingRight: 6,
  },
  swipeActionSurface: {
    flex: 1,
    borderRadius: radius.md,
    overflow: "hidden",
    justifyContent: "center",
  },
  swipeActionMoveSurface: {
    backgroundColor: palette.accentSoft,
    borderWidth: 1,
    borderColor: palette.border,
  },
  swipeActionDeleteSurface: {
    backgroundColor: palette.dangerSoft,
    borderWidth: 1,
    borderColor: "rgba(255, 107, 107, 0.2)",
  },
  swipeActionButton: {
    flex: 1,
    minHeight: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    gap: 2,
  },
  swipeActionButtonPressed: {
    opacity: 0.88,
  },
  swipeActionLabel: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.text,
  },
  swipeActionHint: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    color: palette.textSoft,
  },
  splitLayout: {
    gap: 18,
  },
  splitSidebar: {
    gap: 18,
  },
  splitMain: {
    gap: 18,
  },
  sidebarNavItem: {
    minHeight: 48,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: palette.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sidebarNavItemActive: {
    backgroundColor: palette.surfaceRaised,
  },
  sidebarNavLabel: {
    color: palette.textMuted,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    flex: 1,
  },
  sidebarNavLabelActive: {
    color: palette.text,
  },
  sidebarNavCount: {
    color: palette.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  emptyStateCard: {
    paddingVertical: 28,
    minHeight: 220,
    justifyContent: "center",
  },
  emptyStateTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700",
    color: palette.text,
  },
  emptyStateBody: {
    fontSize: 15,
    lineHeight: 22,
    color: palette.textMuted,
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  drawerOverlay: {
    flex: 1,
    flexDirection: "row",
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.42)",
  },
  drawerPanel: {
    width: "82%",
    maxWidth: 320,
    backgroundColor: palette.canvas,
    borderRightWidth: 1,
    borderRightColor: palette.border,
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 28,
    gap: 18,
  },
  drawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.48)",
  },
  sheetCard: {
    backgroundColor: palette.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 14,
  },
  sheetHandle: {
    width: 48,
    height: 5,
    borderRadius: radius.full,
    alignSelf: "center",
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    marginBottom: 4,
  },
  sheetTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "700",
    color: palette.text,
  },
  sheetSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.textMuted,
  },
  sheetActions: {
    gap: 10,
  },
  sheetButton: {
    minHeight: 52,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.canvasMuted,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetButtonSelected: {
    borderColor: palette.textMuted,
    backgroundColor: palette.surfaceRaised,
  },
  sheetButtonLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: palette.text,
  },
  sheetButtonLabelSelected: {
    color: palette.text,
  },
  sheetButtonLabelDestructive: {
    color: palette.danger,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: palette.canvasStrong,
  },
  bottomBarButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  bottomBarButtonPrimary: {
    backgroundColor: palette.accentDeep,
    borderColor: palette.accentDeep,
  },
  bottomBarButtonLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.text,
  },
  bottomBarButtonLabelPrimary: {
    color: palette.canvasStrong,
  },
  bottomToolbarWrap: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 0,
  },
  bottomToolbar: {
    backgroundColor: palette.canvasStrong,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.lg,
    overflow: "hidden",
  },
  bottomToolbarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
  },
  bottomToolbarSearchButton: {
    minHeight: 52,
    minWidth: 88,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceRaised,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.md,
  },
  bottomToolbarSearchLabel: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.text,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  bottomToolbarButton: {
    flex: 1,
    minHeight: 52,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.lg,
  },
  bottomToolbarButtonPrimary: {
    backgroundColor: palette.accentDeep,
    borderColor: "rgba(255,255,255,0.15)",
  },
  bottomToolbarButtonLabel: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.text,
  },
  bottomToolbarButtonLabelPrimary: {
    color: palette.canvasStrong,
  },
  bottomToolbarSearchPanel: {
    gap: 10,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 12,
    overflow: "hidden",
  },
  bottomToolbarSearchHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  bottomToolbarSearchTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  editorBottomBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: palette.borderSubtle,
    backgroundColor: palette.canvasStrong,
  },
  editorBottomBarSummary: {
    flex: 1,
    gap: 2,
  },
  editorBottomBarLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    color: palette.textSoft,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  editorBottomBarValue: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: palette.text,
  },
  editorBottomBarActions: {
    flexDirection: "row",
    gap: 10,
  },
  editorBottomBarButton: {
    minWidth: 78,
    minHeight: 44,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  editorBottomBarButtonLabel: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: palette.text,
  },
  divider: {
    height: 1,
    backgroundColor: palette.borderSubtle,
  },
  moodPill: {
    minHeight: 38,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceRaised,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  moodPillActive: {
    borderColor: palette.textMuted,
    backgroundColor: palette.accentSoft,
  },
  moodPillLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  moodPillLabelActive: {
    color: palette.accentDeep,
  },
});
