import { StyleSheet } from "react-native";

export const palette = {
  canvas: "#121212",
  canvasMuted: "#1c1c1c",
  canvasStrong: "#0d0d0d",
  surface: "#171717",
  surfaceRaised: "#1e1e1e",
  border: "#2e2e2e",
  text: "#e8e8e8",
  textMuted: "#a8a8a8",
  textSoft: "#787878",
  accent: "#3f3f3f",
  accentDeep: "#f2f2f2",
  accentSoft: "#202020",
  accentWash: "#1a1a1a",
  danger: "#ff6b6b",
  dangerSoft: "#2a1313",
  success: "#66bb8a",
  shadow: "rgba(0, 0, 0, 0.3)",
} as const;

export const commonStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.canvas,
  },
  scrollContent: {
    padding: 20,
    gap: 18,
    paddingBottom: 36,
  },
  screenContent: {
    padding: 20,
    gap: 18,
  },
  card: {
    backgroundColor: palette.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 18,
    gap: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    elevation: 2,
  },
  heroCard: {
    backgroundColor: palette.surfaceRaised,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 22,
    gap: 14,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.09,
    shadowRadius: 28,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 3,
  },
  heroGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: palette.accentWash,
    top: -52,
    right: -48,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    color: palette.accent,
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700",
    color: palette.text,
  },
  headline: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
    color: palette.text,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: palette.textMuted,
  },
  caption: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.textSoft,
  },
  button: {
    minHeight: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.accent,
  },
  buttonSmall: {
    minHeight: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.accent,
  },
  buttonSecondary: {
    minHeight: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.accentSoft,
  },
  buttonSecondarySmall: {
    minHeight: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: palette.accentWash,
  },
  buttonDanger: {
    minHeight: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: palette.dangerSoft,
  },
  buttonLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.text,
  },
  buttonLabelSmall: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.text,
  },
  buttonLabelSecondary: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.accent,
  },
  buttonLabelSecondarySmall: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.accentDeep,
  },
  buttonLabelDanger: {
    fontSize: 15,
    fontWeight: "700",
    color: palette.danger,
  },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceRaised,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: palette.text,
  },
  inputCompact: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceRaised,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: palette.text,
  },
  textArea: {
    minHeight: 180,
    textAlignVertical: "top",
  },
  titleInput: {
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 4,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "700",
    color: palette.text,
  },
  noteBodyInput: {
    minHeight: 320,
    paddingHorizontal: 0,
    paddingTop: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 17,
    lineHeight: 27,
    color: palette.text,
    textAlignVertical: "top",
  },
  row: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  rowWrap: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  rowBetween: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    justifyContent: "space-between",
  },
  chip: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.accentSoft,
    alignSelf: "flex-start",
  },
  chipLabel: {
    color: palette.accent,
    fontSize: 13,
    fontWeight: "600",
  },
  chipMuted: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.canvasMuted,
    alignSelf: "flex-start",
  },
  chipMutedLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "700",
    color: palette.text,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  metricTile: {
    minWidth: 100,
    flexGrow: 1,
    backgroundColor: palette.canvasMuted,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 4,
  },
  metricValue: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: palette.text,
  },
  metricLabel: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: palette.textSoft,
    fontWeight: "700",
  },
  listCard: {
    backgroundColor: palette.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    gap: 10,
  },
  listTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "700",
    color: palette.text,
  },
  listSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.textMuted,
  },
  listHeaderTitle: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "800",
    color: palette.text,
  },
  listHeaderMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: palette.textSoft,
    fontWeight: "600",
  },
  noteRow: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 4,
  },
  noteRowBorder: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  noteMeta: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.textSoft,
  },
  noteTitleRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
  },
  noteTitleCompact: {
    flex: 1,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "700",
    color: palette.text,
  },
  noteDateCompact: {
    fontSize: 12,
    lineHeight: 16,
    color: palette.textSoft,
    fontWeight: "600",
  },
  notePreviewCompact: {
    fontSize: 14,
    lineHeight: 19,
    color: palette.textMuted,
  },
  splitLayout: {
    gap: 18,
  },
  splitSidebar: {
    gap: 18,
  },
  splitMain: {
    gap: 18,
  },
  sidebarNavItem: {
    minHeight: 48,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: palette.canvasMuted,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sidebarNavItemActive: {
    backgroundColor: palette.surfaceRaised,
    borderColor: palette.textMuted,
  },
  sidebarNavLabel: {
    color: palette.textMuted,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    flex: 1,
  },
  sidebarNavLabelActive: {
    color: palette.text,
  },
  sidebarNavCount: {
    color: palette.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  emptyStateCard: {
    paddingVertical: 24,
  },
  emptyStateTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700",
    color: palette.text,
  },
  emptyStateBody: {
    fontSize: 15,
    lineHeight: 22,
    color: palette.textMuted,
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 24,
    minHeight: 56,
    borderRadius: 18,
    paddingHorizontal: 20,
    backgroundColor: palette.accentDeep,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    elevation: 6,
  },
  fabLabel: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
    color: palette.canvasStrong,
  },
  divider: {
    height: 1,
    backgroundColor: palette.border,
  },
  moodPill: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceRaised,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  moodPillActive: {
    borderColor: palette.accent,
    backgroundColor: palette.accentSoft,
  },
  moodPillLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  moodPillLabelActive: {
    color: palette.accentDeep,
  },
});
