/**
 * Every Fluent UI System Icons glyph the apps draw. Names are Fluent's own,
 * without the size and style suffix; a `_filled` suffix selects the filled
 * style instead of regular. `generate.ts` reads exactly this list from
 * `@fluentui/svg-icons`, so adding a glyph means adding its name here and
 * regenerating.
 */
export const GLYPH_NAMES = [
  "add",
  "apps_list",
  "arrow_counterclockwise",
  "arrow_down",
  "arrow_download",
  "arrow_left",
  "arrow_maximize_vertical",
  "arrow_minimize_vertical",
  "arrow_repeat_all",
  "arrow_right",
  "arrow_sort",
  "arrow_swap",
  "arrow_sync",
  "arrow_undo",
  "arrow_up",
  "arrow_upload",
  "attach",
  "board",
  "braces_variable",
  "calendar",
  "calendar_ltr",
  "call",
  "checkbox_checked",
  "checkmark",
  "chevron_down",
  "chevron_left",
  "chevron_right",
  "circle",
  "circle_filled",
  "clock",
  "cloud",
  "cloud_off",
  "code",
  "code_block",
  "color",
  "comment",
  "copy",
  "cursor",
  "data_bar_vertical",
  "database",
  "delete",
  "dismiss",
  "dismiss_square",
  "document_add",
  "document_text",
  "edit",
  "emoji",
  "eraser",
  "flowchart",
  "folder",
  "folder_add",
  "folder_arrow_right",
  "folder_open",
  "full_screen_maximize",
  "full_screen_minimize",
  "highlight",
  "history",
  "image",
  "info",
  "keyboard",
  "line",
  "link",
  "link_dismiss",
  "location",
  "lock_closed",
  "lock_open",
  "mail",
  "maximize",
  "more_horizontal",
  "music_note_2",
  "navigation",
  "note_edit",
  "number_symbol",
  "open",
  "paint_bucket",
  "panel_left",
  "panel_right",
  "pause",
  "people",
  "person",
  "person_circle",
  "picture_in_picture_enter",
  "picture_in_picture_exit",
  "pin",
  "pin_filled",
  "pin_off",
  "play",
  "re_order_dots_vertical",
  "search",
  "settings",
  "share",
  "sign_out",
  "sparkle",
  "speaker_2",
  "speaker_mute",
  "split_horizontal",
  "split_vertical",
  "square",
  "square_multiple",
  "star",
  "subtract",
  "table",
  "tag",
  "task_list_ltr",
  "text_align_center",
  "text_align_left",
  "text_align_right",
  "text_bold",
  "text_bullet_list_ltr",
  "text_case_title",
  "text_font",
  "text_header_1",
  "text_header_2",
  "text_header_3",
  "text_header_4",
  "text_header_5",
  "text_header_6",
  "text_italic",
  "text_number_list_ltr",
  "text_paragraph",
  "text_quote",
  "text_strikethrough",
  "text_whole_word",
  "video",
  "warning",
  "window",
  "zoom_in",
  "zoom_out",
] as const;

export type GlyphName = (typeof GLYPH_NAMES)[number];

/** Fluent draws each glyph on these grids; 24 is the reference. */
export const GLYPH_GRIDS = [20, 24] as const;

export type GlyphGrid = (typeof GLYPH_GRIDS)[number];
