import type { SettingsEntity } from '../types'
import { useSession } from '@/lib/auth-client'
import { STORAGE_KEYS, DEFAULT_IDS } from '@/lib/storage-keys'
import { readOne, create, update } from '@skriuw/crud'
import { GUEST_USER_ID } from '@skriuw/shared'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'

export const settingsKeys = {
	all: ['settings'] as const,
	user: (userId: string | undefined) => [...settingsKeys.all, { userId }] as const
}

export function useSettingsQuery() {
	const { data: session } = useSession()
	const userId = session?.user?.id ?? GUEST_USER_ID

	return useQuery({
		queryKey: settingsKeys.user(userId),
		queryFn: async () => {
			const result = await readOne<SettingsEntity>(
				STORAGE_KEYS.SETTINGS,
				DEFAULT_IDS.SETTINGS,
				{ userId }
			)
			if (!result.success || !result.data) return null
			return result.data
		},
		staleTime: 5 * 60 * 1000
	})
}

export function useSaveSettingsMutation() {
	const queryClient = useQueryClient()
	const { data: session } = useSession()
	const userId = session?.user?.id ?? GUEST_USER_ID

	return useMutation({
		mutationFn: async (settings: Record<string, any>) => {
			// Check existence first for upsert behavior
			const check = await readOne<SettingsEntity>(
				STORAGE_KEYS.SETTINGS,
				DEFAULT_IDS.SETTINGS,
				{ userId }
			)

			if (check.success && check.data) {
				// Update
				const result = await update<SettingsEntity>(
					STORAGE_KEYS.SETTINGS,
					DEFAULT_IDS.SETTINGS,
					{ settings },
					{ userId }
				)
				if (!result.success) throw new Error('Failed to update settings')
				return result.data
			} else {
				// Create - timestamps are auto-generated by storage layer
				const result = await create<SettingsEntity>(
					STORAGE_KEYS.SETTINGS,
					{
						id: DEFAULT_IDS.SETTINGS,
						settings
					} as any,
					{ userId }
				)
				if (!result.success) throw new Error('Failed to create settings')
				return result.data
			}
		},
		onMutate: async (newSettingsMap) => {
			await queryClient.cancelQueries({ queryKey: settingsKeys.user(userId) })
			const previousEntity = queryClient.getQueryData<SettingsEntity>(
				settingsKeys.user(userId)
			)

			queryClient.setQueryData(settingsKeys.user(userId), (old: SettingsEntity | null) => {
				const base: SettingsEntity = old ?? {
					id: DEFAULT_IDS.SETTINGS,
					createdAt: Date.now(),
					updatedAt: Date.now(),
					settings: {}
				}
				const updatedEntity: SettingsEntity = {
					...base,
					settings: { ...base.settings, ...newSettingsMap },
					updatedAt: Date.now()
				}
				return updatedEntity
			})
			return { previousEntity }
		},
		onError: (err, vars, context) => {
			queryClient.setQueryData(settingsKeys.user(userId), context?.previousEntity)
		},
		onSettled: () => {
			queryClient.invalidateQueries({ queryKey: settingsKeys.user(userId) })
		}
	})
}
